---
abstract: 'Interact with FileMaker services'
author:
  - 'Squeeks <squeek@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-FileMaker
requires:
  DateTime::Format::CLDR: 0
  LWP: 0
  URI: 0
  XML::Twig: 3.33
  perl: 5.008001
version: 0.064
