--- #YAML:1.0
name:               Net-FileMaker
version:            0.02
abstract:           Interact with FileMaker Server
author:
    - Squeeks <squeek@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP:          0
    perl:         5.008
    Test::More:   0
    XML::Simple:  2.18
resources:
    repository:  http://github.com/squeeks/Net-FileMaker
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
